debug: false
app_name: Elytra
uuid: ac686df9-66a6-4779-be8a-c37126546681
token_id: REmUq0tU1UVMiBQ2
token: JDY9ylemMOGuOQUd8VzmyrpvNi7wm07lQjqU8QayXOKsFmHLE6CXGXBfVRay4uc8
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.1.48/fullchain.pem
    key: /etc/letsencrypt/live/192.168.1.48/privkey.pem
  disable_remote_download: false
  upload_limit: 100
  trusted_proxies: []
system:
  root_directory: /var/lib/elytra
  log_directory: /var/log/elytra
  data: /var/lib/elytra/volumes
  archive_directory: /var/lib/elytra/archives
  backup_directory: /var/lib/elytra/backups
  tmp_directory: /tmp/elytra
  username: pyrodactyl
  timezone: ""
  user:
    rootless:
      enabled: false
      container_uid: 0
      container_gid: 0
    uid: 8888
    gid: 8888
  passwd:
    enabled: false
    directory: /run/elytra/etc
  disk_check_interval: 150
  activity_send_interval: 60
  activity_send_count: 100
  check_permissions_on_boot: true
  enable_log_rotate: true
  websocket_log_count: 150
  sftp:
    bind_address: 0.0.0.0
    bind_port: 2022
    read_only: false
  crash_detection:
    enabled: true
    detect_clean_exit_as_crash: true
    timeout: 60
  backups:
    write_limit: 0
    compression_level: best_speed
    rustic:
      binary_path: rustic
      local:
        enabled: true
        repository_path: /var/lib/elytra/rustic-repos
        use_cold_storage: false
        hot_repository_path: ""
      s3:
        enabled: false
        endpoint: ""
        region: us-east-1
        bucket: ""
        use_cold_storage: false
        hot_bucket: ""
        cold_storage_class: GLACIER
        force_path_style: false
        disable_ssl: false
        ca_cert_path: ""
      repository_version: 2
      tree_pack_size_mb: 4
      data_pack_size_mb: 32
  transfers:
    download_limit: 0
  openat_mode: auto
docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    network_mtu: 1500
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
  container_pid_limit: 512
  installer_limits:
    memory: 1024
    cpu: 100
  overhead:
    override: false
    default_multiplier: 1.05
    multipliers: {}
  use_performant_inspect: true
  userns_mode: ""
  log_config:
    type: local
    config:
      compress: "false"
      max-file: "1"
      max-size: 5m
      mode: non-blocking
throttles:
  enabled: true
  lines: 2000
  line_reset_interval: 100
remote: https://panel.smeagol.me
remote_query:
  timeout: 30
  boot_servers_per_page: 50
allowed_mounts: []
allowed_origins:
- https://panel.smeagol.me
allow_cors_private_network: false
ignore_panel_config_updates: false
